server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名称进行路由(默认false)
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
          #  - After=2020-04-04T22:53:53.458+08:00[Asia/Shanghai] #指定时间后才能访问（After）时间往后写一小时 ZonedDateTime now = ZonedDateTime.now();
          #  - Before=2020-06-17T11:53:40.325+08:00[Asia/Shanghai] #指定时间前才能访问（Before）
          #  - Between=2020-06-17T11:53:40.325+08:00[Asia/Shanghai],2020-06-17T12:53:40.325+08:00[Asia/Shanghai] #指定时间内才能访问（Between）
          #  - Cookie=username,angenin   #带Cookie，并且username的值为angenin
          #  - Header=X-Request-Id, \d+   #请求头要有 X-Request-Id属性并且值为整数的正则表达式
          #  - Host=**.angenin.com    #Host: xxx.angenin.com 请求是Host必须有**.angenin.com
          #  - Method=GET	#只允许get请求访问
          #  - Query=username, \d+   #url请求地址必须带上username参数，并且值必须为整数

        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/